---
# https://taskfile.dev
version: '3'
tasks:
  req:
    desc: 🛠️ [agent_llamaindex] Update local dependencies
    cmds:
      - echo "Updating local dependencies"
      - uv sync --all-extras
      - uv pip install --no-cache-dir git+https://github.com/BerriAI/litellm@v1.72.1.dev1
      - cd custom_model && uv pip install -r requirements.txt
    silent: true
  lint:
    desc: 🧹 [agent_llamaindex] Lint the codebase
    cmds:
      - task: req
      - echo "Linting the codebase"
      - uv run ruff check . --fix
      - uv run ruff format .
      - uv run mypy --pretty .
      - uv run yamlfix custom_model
    silent: true
  lint-check:
    desc: 🧹 [agent_llamaindex] Check whether the codebase is linted
    cmds:
      - task: req
      - echo "Checking linting"
      - uv run ruff format --check --diff .
      - uv run ruff check --diff .
      - uv run mypy --pretty .
    silent: true
  test:
    desc: 🧪 [agent_llamaindex] Run tests
    cmds:
      - echo "Running pytest on tests"
      - uv run pytest -vv ./tests/
    silent: true
  test-coverage:
    desc: 🧪 [agent_llamaindex] Run tests with coverage
    cmds:
      - echo "Running pytest on tests"
      - uv run pytest -vv --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml ./tests/
    silent: true
  cli:
    desc: 🖥️ [agent_llamaindex] Run the CLI with provided arguments
    cmds:
      - echo "Running CLI {{.CLI_ARGS}}"
      - uv run cli.py {{.CLI_ARGS}}
    silent: true
