---
# https://taskfile.dev
version: '3'
env:
  ENV: testing
dotenv: ['.env', '.env.{{.ENV}}']
includes:
  agent:
    taskfile: ./agent_langgraph/Taskfile.yml
    dir: ./agent_langgraph
  fastapi:
    taskfile: ./fastapi/Taskfile.yaml
    dir: ./fastapi
tasks:
  default:
    desc: "🗒️ Show all available tasks"
    cmds:
      - task --list
    silent: true
  install:
    desc: "🏗️ Install and setup the components"
    cmds:
      - echo "Updating agent environment"
      - task: agent:install
      - echo "Updating fastapi environment"
      - task: fastapi:install
      - echo "Updating infra environment"
      - cd ./infra && uv sync --all-extras
    silent: true
    aliases:
      - setup
      - req
  dev:
    desc: "🔨Run the fastapi development server"
    deps:
      - fastapi:dev-agent
      - agent:dev
    silent: true
  build:
    desc: "🔵 [agent_langgraph] Run Pulumi up in [BUILD] mode"
    env:
      AGENT_DEPLOY: 0
    cmds:
      - echo "Running pulumi up with [BUILD] mode"
      - cd ./infra && uv run pulumi up {{.CLI_ARGS}}
    silent: true
  deploy:
    desc: "🟢 [agent_langgraph] Run Pulumi up in [DEPLOY] mode"
    env:
      AGENT_DEPLOY: 1
    cmds:
      - echo "Running pulumi up with [DEPLOY] mode"
      - cd ./infra && uv run pulumi up {{.CLI_ARGS}}
    silent: true
  refresh:
    desc: "⚪️ [agent_langgraph] Run Pulumi refresh"
    cmds:
      - echo "Running pulumi refresh"
      - cd ./infra && uv run pulumi refresh {{.CLI_ARGS}}
    silent: true
  destroy:
    desc: "🔴 [agent_langgraph] Run Pulumi destroy"
    cmds:
      - echo "Running pulumi destroy"
      - cd ./infra && uv run pulumi destroy {{.CLI_ARGS}}
    silent: true
