---
# https://taskfile.dev
version: '3'
env:
  ENV: testing
dotenv: ['.env', '.env.{{.ENV}}']
includes:
  agent_crewai:
    taskfile: ./Taskfile_agent_crewai.yml
    dir: .
    internal: true
  agent_generic_base:
    taskfile: ./Taskfile_agent_generic_base.yml
    dir: .
    internal: true
  agent_langgraph:
    taskfile: ./Taskfile_agent_langgraph.yml
    dir: .
    internal: true
  agent_llamaindex:
    taskfile: ./Taskfile_agent_llamaindex.yml
    dir: .
    internal: true
  development:
    taskfile: ./Taskfile_development.yml
    dir: .
tasks:
  default:
    desc: "Show all available tasks"
    cmds:
      - task --list
    silent: true
  start:
    desc: "‼️ Quickstart for DataRobot Agent Templates ‼️"
    cmds:
      - uv run quickstart.py
  install:
    desc: "Install dependencies for all agent components and infra"
    cmds:
      - echo "Updating dependencies for all agents"
      - task: agent_crewai:agent:req
      - task: agent_generic_base:agent:req
      - task: agent_langgraph:agent:req
      - task: agent_llamaindex:agent:req
      - echo "Updating infra dependencies"
      - cd ./infra && uv sync --all-extras
    silent: true
    aliases:
      - req
      - install-all
  update:
    desc: "Update all dependencies for all agent components and infra (refresh uv locks)"
    cmds:
      - echo "Updating dependencies for all agents"
      - task: agent_crewai:agent:update
      - task: agent_generic_base:agent:update
      - task: agent_langgraph:agent:update
      - task: agent_llamaindex:agent:update
      - echo "Updating infra dependencies"
      - cd ./infra && uv sync --all-extras -U
    silent: true
    aliases:
      - update-all
  lint:
    desc: "Lint all agent components and infra"
    cmds:
      - echo "Linting all agent templates"
      - task: agent_crewai:agent:lint
      - task: agent_generic_base:agent:lint
      - task: agent_langgraph:agent:lint
      - task: agent_llamaindex:agent:lint
      - echo "Linting infra"
      - cd ./infra && uv run ruff check . --fix && uv run ruff format .
    silent: true
