---
# https://taskfile.dev
version: '3'
env:
  ENV: testing
dotenv: ['.env', '.env.{{.ENV}}']
vars:
  COMPONENTS: agent_crewai agent_generic_base agent_langgraph agent_llamaindex infra
includes:
  development:
    taskfile: ./Taskfile_development.yml
    dir: .
  execenv:
    taskfile: ./Taskfile_execution_env.yml
    dir: .
tasks:
  default:
    desc: "Show all available tasks"
    cmds:
      - task --list
    silent: true
  start:
    desc: "‼️ Quickstart for DataRobot Agent Templates ‼️"
    cmds:
      - uv run quickstart.py
  install:
    desc: "Install dependencies for all agent components and infra"
    cmds:
      - for: { var: COMPONENTS }
        cmd: task --dir {{.ITEM}} req
    silent: true
    aliases:
      - req
      - install-all
  update:
    desc: "Update all dependencies for all agent components and infra (refresh uv locks)"
    cmds:
      - for: { var: COMPONENTS }
        cmd: task --dir {{.ITEM}} update
    silent: true
    aliases:
      - update-all
  lint:
    desc: "Lint all agent components and infra"
    cmds:
      - for: { var: COMPONENTS }
        cmd: task --dir {{.ITEM}} lint
    silent: true
  test_api_tests:
    desc: "Run API tests"
    cmds:
      - echo "Running pytest on api_tests"
      - cd ./api_tests && uv run pytest -vv -s ./api_tests/
    silent: true
