---
# https://taskfile.dev
version: '3'
env:
  ENV: testing
dotenv: ['.env', '.env.{{.ENV}}']
tasks:
  default:
    desc: "Show all available tasks"
    cmds:
      - task --list
    silent: true
  req:
    desc: "Install dependencies for all agent components and infra"
    cmds:
      - echo "Updating api test dependencies"
      - uv sync --all-extras
    silent: true
  lint:
    desc: 🧹 Lint api tests
    cmds:
      - task: req
      - echo "Linting api test"
      - uv run ruff check . --fix
      - uv run ruff format .
      - uv run mypy --pretty .
    silent: true
  lint-check:
    desc: ✅ Check lint for api tests
    cmds:
      - task: req
      - echo "Checking linting"
      - uv run ruff format --check --diff .
      - uv run ruff check --diff .
      - uv run mypy --pretty .
    silent: true
  build:
    desc: "🐳 Build the API test Docker image"
    cmds:
      - cd .. && docker build -f api_tests/docker_context/Dockerfile . -t test
    silent: true
  test:
    desc: "🧪 Run all API tests"
    cmds:
      - task: build
      - docker run --env-file .env -t test base
      - docker run --env-file .env -t test crewai
      - docker run --env-file .env -t test langgraph
      - docker run --env-file .env -t test llamaindex
    silent: true
  test-base:
    desc: "🤖 Run base agent API tests"
    cmds:
      - echo "Running base agent tests"
      - task: build
      - docker run --env-file .env -t test base
    silent: true
  test-crewai:
    desc: "👥 Run crewai agent API tests"
    cmds:
      - echo "Running crewai agent tests"
      - task: build
      - docker run --env-file .env -t test crewai
    silent: true
  test-langgraph:
    desc: "🔄 Run langgraph agent API tests"
    cmds:
      - echo "Running langgraph agent tests"
      - task: build
      - docker run --env-file .env -t test langgraph
    silent: true
  test-llamaindex:
    desc: "🦙 Run llamaindex agent API tests"
    cmds:
      - echo "Running llamaindex agent tests"
      - task: build
      - docker run --env-file .env -t test llamaindex
    silent: true
