---
name: Test agent_langgraph

on:
  push:
    branches: ["main"]
    paths:
      - 'agent_langgraph/**.py'

  pull_request:
    branches: ["main"]
    paths:
      - 'agent_langgraph/**.py'

jobs:
  tests:
    name: "Agent: agent_langgraph ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: agent_langgraph

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: "actions/checkout@v4"

      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: agent_langgraph
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: agent_langgraph
        run: |
          uv sync --all-extras --dev
          uv pip install git+https://github.com/datarobot-forks/litellm@mattn/add-datarobot-support-to-litellm
          uv pip install -r ./custom_model/requirements.txt

      - name: Run Static Checks
        working-directory: agent_langgraph
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy --pretty .

      - name: Test
        working-directory: agent_langgraph
        run: uv run pytest --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: agent_langgraph/.coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
