---
name: Test agent_crewai

on:
  push:
    branches: ["main"]
    paths:
      - 'agent_crewai/**.py'

  pull_request:
    branches: ["main"]
    paths:
      - 'agent_crewai/**.py'

jobs:
  tests:
    name: "Agent: agent_crewai ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: agent_crewai

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: "actions/checkout@v4"

      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: agent_crewai
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: agent_crewai
        run: uv sync --all-extras --dev

      - name: Run Static Checks
        working-directory: agent_crewai
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy --pretty .

      - name: Test
        working-directory: agent_crewai
        run: uv run pytest --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: agent_crewai/.coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
