---
name: Test agent_generic_base

on:
  push:
    branches: ["main"]
    paths:
      - 'agent_generic_base/**.py'
      - 'agent_generic_base/**.yml'
      - 'agent_generic_base/**.txt'
      - 'agent_generic_base/**.sh'

  pull_request:
    branches: ["main"]
    paths:
      - 'agent_generic_base/**.py'
      - 'agent_generic_base/**.yml'
      - 'agent_generic_base/**.txt'
      - 'agent_generic_base/**.sh'

jobs:
  docker-build-test:
    name: "Docker Build and Test"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: agent_generic_base/docker_context
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Build Docker Image
        run: docker build . -t agent_generic_base

  drum-cli-tests:
    name: "DRUM: agent cli ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: agent_generic_base

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: "actions/checkout@v4"

      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: agent_generic_base
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: agent_generic_base
        run: |
          uv sync --all-extras
          uv pip install git+https://github.com/datarobot-forks/litellm@mattn/add-datarobot-support-to-litellm

      - name: Run cli test
        working-directory: agent_generic_base
        run: |
          uv run cli.py execute --user_prompt '{"topic": "Artificial Intelligence"}'
          if uv run cli.py execute --user_prompt '{"topic": "Artificial Intelligence"}' | grep -q '"content": "success"'; then
            echo "Test passed: cli.py returned success"
          else
            echo "Test failed: cli.py did not return success"
            exit 1
          fi

  tests:
    name: "Agent: agent_generic_base ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: agent_generic_base

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: "actions/checkout@v4"

      # Ref: https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: agent_generic_base
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: agent_generic_base
        run: |
          uv sync --all-extras --dev
          uv pip install git+https://github.com/datarobot-forks/litellm@mattn/add-datarobot-support-to-litellm
          uv pip install -r ./custom_model/requirements.txt

      - name: Run Static Checks
        working-directory: agent_generic_base
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy --pretty .

      - name: Test
        working-directory: agent_generic_base
        run: uv run pytest --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: agent_generic_base/.coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
