---
name: API Tests
on:
  push:
    branches: ["main"]
    paths:
      - 'api_tests/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'api_tests/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: api_tests
jobs:
  uvx-copier-lint-test:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Lint Template
        run: |
          cd ./api_tests
          task lint-check
